### PR TITLE
First upload

### PR DESCRIPTION
**Pull request by ericboucher**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/teradata-connector/1)

### CODE REVIEW

**Comment by ericboucher** [comment]
@mjamei will we add circle-ci? If not, I think I will remove the drivers and add a Readme on how to obtain them. What do you think?

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-:-KhcPMtwd3T5Uko98Dvu:b-h06es4)*

**Comment by mjamei** [comment]
Let's keep CC for now. right now it's failing because it can't find any tests. Also what do you think about removing the Jupyter notebook from the docker? Seems not to be important here.

---

Review status: 0 of 12 files reviewed at latest revision, 8 unresolved discussions.

---

*[docker-compose.yml, line 8 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcUOwRj0P1wfdFzDMs:-KhcUOwRj0P1wfdFzDMt:b-vd2udj) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/docker-compose.yml#L8)):*
> ```YAML
>     ports:
>       - "8888:8888"
>     command: /usr/local/bin/start-notebook.sh --NotebookApp.token='' --NotebookApp.ip='*' --debug
> ```

why are we starting Jupyter notebook when calling `teradata`? the naming is confusing.

---

*[Dockerfile, line 13 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcUzlTtySDG5Px0y6I:-KhcUzlTtySDG5Px0y6J:ba1vzzo) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/Dockerfile#L13)):*
> ```Dockerfile
> RUN yum install -y libxml2-devel libxml++-devel python-devel
> 
> # Download Python and compile
> ```

Specify the python version that you are installing

---

*[Dockerfile, line 32 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcUdHR5xBYgb1RwDJ5:-KhcUdHR5xBYgb1RwDJ6:bxc23wt) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/Dockerfile#L32)):*
> ```Dockerfile
> ENV ODBCINST /app/vendored/teradata/client/ODBC_64/odbcinst.ini
> # RUN epxort ODBCINI
> # RUN export ODBCINST
> ```

If you don't need these two lines, just remove them. There's also a typo here.

---

*[Dockerfile, line 40 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcUtNWcjMAb7yrDeda:-KhcUtNWcjMAb7yrDedb:b-2pi10g) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/Dockerfile#L40)):*
> ```Dockerfile
> # Install Jupyter Notebook
> RUN python -m pip install --upgrade --force pip
> RUN pip install jupyter
> ```

You install both Jupyter and ipython notebooks. remove one of them.

---

*[install_teradata_drivers.sh, line 5 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcVGXxM-rgb_nLLoYk:-KhcVGXxM-rgb_nLLoYl:bmzxxwr) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/install_teradata_drivers.sh#L5)):*
> ```Shell
> mkdir -p /app/install/
> mkdir -p /app/vendored/
> cp /code/tdodbc1510__linux_indep.15.10.01.05-1.tar /app/install/
> ```

do you want to move it here? You have two copy of the this file in the docker. Does it have to be moved before decompression?

---

*[requirements.txt, line 7 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcXgn91aNO9B1puV2B:-KhcXgn91aNO9B1puV2C:b5tdn9h) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/requirements.txt#L7)):*
> ```
> pandas==0.19.2
> pytest==2.9.0
> teradata==15.10.0.20
> ```

Most of these requirements are not needed. Just keep the ones that we absolutely need for this docker.

---

*[teradata_test_connect.py, line 25 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcWaPQnmpMqcn3TfGZ:-KhcWaPQnmpMqcn3TfG_:b16hp1l) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/teradata_test_connect.py#L25)):*
> ```Python
>         print('Drivers seem properly installed.')
>     except teradata.DatabaseError as e:
>         print('Drivers seem properly installed.')
> ```

do you want to say do not seem properly installed?

---

*[teradata_test_connect.py, line 27 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcWgiWRTYJZOw7ToZz:-KhcWgiWRTYJZOw7To_-:bcm4acb) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/teradata_test_connect.py#L27)):*
> ```Python
>         print('Drivers seem properly installed.')
>     except OSError as e:
>         print('CreateTDConnection:Failed to Conect to teradata server', e)
> ```

typo: connect

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-:-KhcXPjqi5oXznOtG7vH:b-80a24n)*

**Comment by mjamei** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1)*

**Comment by ericboucher** [comment]
Review status: 7 of 12 files reviewed at latest revision, 8 unresolved discussions.

---

*[docker-compose.yml, line 8 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcUOwRj0P1wfdFzDMs:-KhdK613Zl9Ga337niI_:b-896fix) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/docker-compose.yml#L8)):*
<details><summary><i>Previously, mjamei (Mehdi Jamei) wrote…</i></summary><blockquote>

why are we starting Jupyter notebook when calling `teradata`? the naming is confusing.
</blockquote></details>

Done.

---

*[Dockerfile, line 13 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcUzlTtySDG5Px0y6I:-KhdK8tpNNSeu7szw9j_:b-896fix) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/Dockerfile#L13)):*
<details><summary><i>Previously, mjamei (Mehdi Jamei) wrote…</i></summary><blockquote>

Specify the python version that you are installing
</blockquote></details>

Done.

---

*[Dockerfile, line 32 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcUdHR5xBYgb1RwDJ5:-KhdK9dMhLPtLDTP8bco:b-896fix) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/Dockerfile#L32)):*
<details><summary><i>Previously, mjamei (Mehdi Jamei) wrote…</i></summary><blockquote>

If you don't need these two lines, just remove them. There's also a typo here.
</blockquote></details>

Done.

---

*[Dockerfile, line 40 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcUtNWcjMAb7yrDeda:-KhdKA8a7bD4bKZ5bO53:b-896fix) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/Dockerfile#L40)):*
<details><summary><i>Previously, mjamei (Mehdi Jamei) wrote…</i></summary><blockquote>

You install both Jupyter and ipython notebooks. remove one of them.
</blockquote></details>

Done.

---

*[install_teradata_drivers.sh, line 5 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcVGXxM-rgb_nLLoYk:-KhdOQy_3ndkYREG0E_p:b-896fix) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/install_teradata_drivers.sh#L5)):*
<details><summary><i>Previously, mjamei (Mehdi Jamei) wrote…</i></summary><blockquote>

do you want to move it here? You have two copy of the this file in the docker. Does it have to be moved before decompression?
</blockquote></details>

Done.

---

*[requirements.txt, line 7 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcXgn91aNO9B1puV2B:-KhdKTFn7pwc8fv19Kjc:b-896fix) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/requirements.txt#L7)):*
<details><summary><i>Previously, mjamei (Mehdi Jamei) wrote…</i></summary><blockquote>

Most of these requirements are not needed. Just keep the ones that we absolutely need for this docker.
</blockquote></details>

Done.

---

*[teradata_test_connect.py, line 25 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcWaPQnmpMqcn3TfGZ:-KhdKV91sqAb3wUcE-YI:bg9tnue) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/teradata_test_connect.py#L25)):*
<details><summary><i>Previously, mjamei (Mehdi Jamei) wrote…</i></summary><blockquote>

do you want to say do not seem properly installed?
</blockquote></details>

nope, database error should be fine. Other errors would not be

---

*[teradata_test_connect.py, line 27 at r1](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhcWgiWRTYJZOw7ToZz:-KhdKbyG7scjQ8RB_0P_:b-896fix) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/8b0855a50fd0919d12d47a30283858a5c3fa3d5e/teradata_test_connect.py#L27)):*
<details><summary><i>Previously, mjamei (Mehdi Jamei) wrote…</i></summary><blockquote>

typo: connect
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1)*

**Comment by mjamei** [comment]
Review status: 7 of 12 files reviewed at latest revision, 10 unresolved discussions.

---

*[docker-compose.yml, line 7 at r2](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhdQCEnIuAhpd8iHNTq:-KhdQCEo_Noe2ElthGB1:b-63f5dq) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/7c46f2f4cb7a151db9fc60887fd0c17bb8becdba/docker-compose.yml#L7)):*
> ```YAML
>       context: .
>     volumes:
>       - ./Makefile:/home/nbuser/work/Makefile:ro
> ```

I'd rename `nbuser` here.

---

*[Dockerfile, line 52 at r2](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhdPz-OeDSMD6_YVtXx:-KhdPz-OeDSMD6_YVtXy:b5xeahc) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/7c46f2f4cb7a151db9fc60887fd0c17bb8becdba/Dockerfile#L52)):*
> ```Dockerfile
> RUN mkdir /home/$NB_USER/.jupyter
> RUN mkdir /home/$NB_USER/.local
> WORKDIR /home/$NB_USER/work
> ```

Also these are not needed anymore. `NB_USER` should be renamed because you don't have notebook users.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1)*

**Comment by mjamei** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-:-KhdQOeSkie3bK59rVCM:bnfp4nl)*

**Comment by mjamei** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1)*

**Comment by ericboucher** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[docker-compose.yml, line 7 at r2](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhdQCEnIuAhpd8iHNTq:-Khdw5QDOW-v3-wWLwaQ:b-896fix) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/7c46f2f4cb7a151db9fc60887fd0c17bb8becdba/docker-compose.yml#L7)):*
<details><summary><i>Previously, mjamei (Mehdi Jamei) wrote…</i></summary><blockquote>

I'd rename `nbuser` here.
</blockquote></details>

Done.

---

*[Dockerfile, line 52 at r2](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhdPz-OeDSMD6_YVtXx:-Khdw4awl1njEBOCUjW2:b-896fix) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/7c46f2f4cb7a151db9fc60887fd0c17bb8becdba/Dockerfile#L52)):*
<details><summary><i>Previously, mjamei (Mehdi Jamei) wrote…</i></summary><blockquote>

Also these are not needed anymore. `NB_USER` should be renamed because you don't have notebook users.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1)*

**Comment by ericboucher** [comment]
+@tetraptych 

---

Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-:-KhdzGfw6NN-GhLhdUxl:b-llq6g2)*

**Comment by tetraptych** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-:-Khh8RYRh1ggh6jvhjNo:bnfp4nl)*

**Comment by ericboucher** [comment]
@mjamei looks like reviewable would like a second LGTM for some reason?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-:-KhhJNPC3ygZH2vUMCfn:b-xb9hae)*

**Comment by ericboucher** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[docker-compose.yml, line 7 at r2](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhdQCEnIuAhpd8iHNTq:-KhhJT4Nyy0Qc8sGjYLT:b-896fix) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/7c46f2f4cb7a151db9fc60887fd0c17bb8becdba/docker-compose.yml#L7)):*
<details><summary><i>Previously, ericboucher (Eric Boucher) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[Dockerfile, line 52 at r2](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-KhdPz-OeDSMD6_YVtXx:-KhhJTaOShszMRbK-Dmp:b-896fix) ([raw file](https://github.com/bayesimpact/teradata-connector/blob/7c46f2f4cb7a151db9fc60887fd0c17bb8becdba/Dockerfile#L52)):*
<details><summary><i>Previously, ericboucher (Eric Boucher) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1)*

**Comment by mjamei** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/teradata-connector/1#-:-KhhQqCmWVElr4AhZdsW:bnfp4nl)*

**Pull request merged**
